# -Activate Profile
spring:
  profiles:
    active: dev
---
# Define  dev profile
spring:
   config:
      activate:
          on-profile: dev
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       password: root
       url: jdbc:mysql:///NTSPBMS1103DB
       type: org.apache.commons.dbcp2.BasicDataSource
---
# Define  test profile
 spring:
    config:
      activate:
         on-profile: test
    datasource:
           driver-class-name: com.mysql.cj.jdbc.Driver
           username: root
           password: root
           url: jdbc:mysql:///NTSPBMS1103DB
           type: com.mchange.v2.c3p0.ComboPooledDataSource
---
#Define  test profile
 spring:
    config:
        activate:
           on-profile: uat
    datasource:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: system
          password: tiger
          url: jdbc:oracle:thin:@localhost:1521:xe
          type: oracle.ucp.jdbc.PoolDataSourceImpl
---
# Define  prod profile
spring:
    config:
       activate:
          on-profile: prod
    datasource:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: system
          password: tiger
          url: jdbc:oracle:thin:@localhost:1521:xe 	

   